set(LAUNCHER_ORGANISATION "AttorneyOnline")
set(LAUNCHER_NAME "AOLauncher")
set(LAUNCHER_GUID_IDENTIFIER com.aceattorneyonline.${LAUNCHER_NAME})
set(LAUNCHER_VERSION_MAJOR 0)
set(LAUNCHER_VERSION_MINOR 1)
set(LAUNCHER_VERSION_PATCH 0)
set(LAUNCHER_VERSION "${LAUNCHER_VERSION_MAJOR}.${LAUNCHER_VERSION_MINOR}.${LAUNCHER_VERSION_PATCH}")

message(STATUS "LAUNCHER_VERSION" " ${LAUNCHER_VERSION}")
