name: CI

on: [push, pull_request]

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: ./libs/libarchive/build/ci/github_actions/macos.sh prepare
    - name: Autogen
      run: ./libs/libarchive/build/ci/build.sh -a autogen
      env:
        BS: cmake
    - name: Configure
      run: ./libs/libarchive/build/ci/build.sh -a configure
      env:
        BS: cmake
    - name: Build
      run: ./libs/libarchive/build/ci/build.sh -a build
      env:
        BS: cmake
    - name: Test
      run: ./libs/libarchive/build/ci/build.sh -a test
      env:
        BS: cmake
        SKIP_OPEN_FD_ERR_TEST: 1
    - name: Install
      run: ./libs/libarchive/build/ci/build.sh -a install
      env:
        BS: cmake
    - name: Artifact
      run: ./libs/libarchive/build/ci/build.sh -a artifact
      env:
        BS: cmake

    - name: Setup Qt
      uses: Skycoder42/action-setup-qt@master
      id: qt
      with:
        version: 5.15.1
        platform: gcc_64

    - name: QMake
      run: |
        qmake

    - name: Make
      run: |
        ${{steps.qt.outputs.make}}

    - uses: actions/upload-artifact@v1
      with:
        name: libarchive-macos-${{ github.sha }}
        path: libarchive.tar.xz

  Ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master

    - name: Install dependencies
      run: sudo apt-get install -y autoconf automake build-essential cmake git libssl-dev nettle-dev libmbedtls-dev libacl1-dev libbz2-dev liblzma-dev liblz4-dev libzstd-dev lzop pkg-config zlib1g-dev

    - name: Autogen
      run: ./libs/libarchive/build/ci/build.sh -a autogen
      env:
        BS: cmake

    - name: Configure
      run: ./libs/libarchive/build/ci/build.sh -a configure
      env:
        BS: cmake
        CRYPTO: mbedtls

    - name: Build
      run: ./libs/libarchive/build/ci/build.sh -a build
      env:
        BS: cmake

    - name: Test
      run: ./libs/libarchive/build/ci/build.sh -a test
      env:
        BS: cmake
        SKIP_OPEN_FD_ERR_TEST: 1

    - name: Install
      run: ./libs/libarchive/build/ci/build.sh -a install
      env:
        BS: cmake

    - name: Artifact
      run: ./libs/libarchive/build/ci/build.sh -a artifact
      env:
        BS: cmake

    - name: Setup Qt
      uses: Skycoder42/action-setup-qt@master
      id: qt
      with:
        version: 5.15.1
        platform: gcc_64

    - name: QMake
      run: |
        qmake

    - name: Make
      run: |
        ${{steps.qt.outputs.make}}

    - uses: actions/upload-artifact@v1
      with:
        name: libarchive-ubuntu-${{ github.sha }}
        path: libarchive.tar.xz

  Windows:
    runs-on: windows-2022
    strategy:
      matrix:
        be: [mingw-gcc, msvc]
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: ./libs/libarchive/build/ci/github_actions/ci.cmd deplibs
      shell: cmd
      env:
        BE: ${{ matrix.be }}
    - name: Configure
      run: ./libs/libarchive/build/ci/github_actions/ci.cmd configure
      shell: cmd
      env:
        BE: ${{ matrix.be }}
    - name: Build
      run: ./libs/libarchive/build/ci/github_actions/ci.cmd build
      shell: cmd
      env:
        BE: ${{ matrix.be }}
    - name: Test
      run: ./libs/libarchive/build/ci/github_actions/ci.cmd test
      shell: cmd
      env:
        BE: ${{ matrix.be }}
    - name: Install
      run: ./libs/libarchive/build/ci/github_actions/ci.cmd install
      shell: cmd
      env:
        BE: ${{ matrix.be }}
    - name: Artifact
      run: ./libs/libarchive/build/ci/github_actions/ci.cmd artifact
      shell: cmd
      env:
        BE: ${{ matrix.be }}

    - name: Setup Qt
      uses: Skycoder42/action-setup-qt@master
      id: qt
      with:
        version: 5.15.1
        platform: gcc_64

    - name: QMake
      run: |
        qmake

    - name: Make
      run: |
        ${{steps.qt.outputs.make}}

    - uses: actions/upload-artifact@v1
      with:
        name: libarchive-windows-${{ matrix.be }}-${{ github.sha }}
        path: libarchive.zip
