name: CI

on: [push, pull_request]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Install dependencies
      working-directory: ${{github.workspace}}/libs/libarchive/
      run: ./build/ci/github_actions/macos.sh prepare

    - name: Autogen
      working-directory: ${{github.workspace}}/libs/libarchive/
      run: ./build/ci/build.sh -a autogen
      env:
        BS: cmake

    - name: Configure
      working-directory: ${{github.workspace}}/libs/libarchive/
      run: ./build/ci/build.sh -a configure
      env:
        BS: cmake

    - name: Build
      working-directory: ${{github.workspace}}/libs/libarchive/
      run: ./build/ci/build.sh -a build
      env:
        BS: cmake

    - name: Install
      working-directory: ${{github.workspace}}/libs/libarchive/
      run: ./build/ci/build.sh -a install
      env:
        BS: cmake

    - name: Upgrade Python
      run: |
        brew install python


    - name: Setup Qt
      uses: Skycoder42/action-setup-qt@master
      id: qt
      with:
        version: 5.15.3
        platform: gcc_64

    - name: QMake
      run: |
        qmake

    - name: Make
      run: |
        ${{steps.qt.outputs.make}}

    - uses: actions/upload-artifact@v3
      with:
        name: launcher-macos-${{ github.sha }}
        path: ${{ github.workspace }}/launcher/bin/

  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install -y autoconf automake build-essential cmake git libarchive-dev libssl-dev nettle-dev libmbedtls-dev libacl1-dev libbz2-dev liblzma-dev liblz4-dev libzstd-dev lzop pkg-config zlib1g-dev

    - name: Autogen
      working-directory: ${{github.workspace}}/libs/libarchive/
      run: ./build/ci/build.sh -a autogen
      env:
        BS: cmake

    - name: Configure
      working-directory: ${{github.workspace}}/libs/libarchive/
      run: ./build/ci/build.sh -a configure
      env:
        BS: cmake
        CRYPTO: mbedtls

    - name: Build
      working-directory: ${{github.workspace}}/libs/libarchive/
      run: ./build/ci/build.sh -a build
      env:
        BS: cmake

    - name: Install
      working-directory: ${{github.workspace}}/libs/libarchive/
      run: ./build/ci/build.sh -a install
      env:
        BS: cmake

    - name: Artifact
      working-directory: ${{github.workspace}}/libs/libarchive/
      run: ./build/ci/build.sh -a artifact
      env:
        BS: cmake

    - name: Setup Qt
      uses: Skycoder42/action-setup-qt@master
      id: qt
      with:
        version: 5.15.3
        platform: gcc_64

    - name: QMake
      run: |
        qmake

    - name: Make
      run: |
        ${{steps.qt.outputs.make}}

    - uses: actions/upload-artifact@v3
      with:
        name: launcher-ubuntu-${{ github.sha }}
        path: ${{ github.workspace }}/launcher/bin/

  Windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Install dependencies
      working-directory: ${{github.workspace}}/libs/libarchive/
      run: ./build/ci/github_actions/ci.cmd deplibs
      shell: cmd
      env:
        BE: msvc

    - name: Configure
      working-directory: ${{github.workspace}}/libs/libarchive/
      run: ./build/ci/github_actions/ci.cmd configure
      shell: cmd
      env:
        BE: msvc

    - name: Build
      working-directory: ${{github.workspace}}/libs/libarchive/
      run: ./build/ci/github_actions/ci.cmd build
      shell: cmd
      env:
        BE: msvc

    - name: Install
      working-directory: ${{github.workspace}}/libs/libarchive/
      run: ./build/ci/github_actions/ci.cmd install
      shell: cmd
      env:
        BE: msvc

    - name: Setup Qt
      uses: Skycoder42/action-setup-qt@master
      id: qt
      with:
        version: 5.15.3
        platform: msvc2019

    - name: QMake
      run: |
        qmake

    - name: Make
      run: |
        ${{steps.qt.outputs.make}}

    - uses: actions/upload-artifact@v3
      with:
        name: launcher-windows-msvc-${{ github.sha }}
        path: ${{ github.workspace }}/launcher/bin/
